export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const DONE_TODO = "DONE_TODO";
export const ALL_USERS = "ALL_USERS";
export const NEW_USER = "NEW_USER";
export const USER_LEAVED = "USER_LEAVED";
export const USER_PROFILE = "USER_PROFILE";
export const PEER_CONNECTION = "CONNECTION";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_FAILED = "ALL_USERS_FAILED";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const SELECT_MESSAGES = "SELECT_MESSAGES";
export const ADD_MESSAGES = "ADD_MESSAGES";
export const ADD_GMESSAGES = "ADD_GMESSAGES";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const NEW_GMESSAGE = "NEW_GMESSAGE";
export const GROUP_SELECTION = "GROUP_SELECTION";
export const USER_SELECTION = "USER_SELECTION";
export const GROUP_SELECTED = "GROUP_SELECTED";
export const MESSAGE_SEEN = "MESSAGE_SEEN";

export const AdminChatActions = {
  ADD_VISITORS_LIST: "ADD_VISITORS_LIST",
  ADD_VISITOR: "ADD_VISITOR",
  LEAVE_VISITOR: "LEAVE_VISITOR",
  REJOIN_VISITOR: "REJOIN_VISITOR",
  ADD_MESSAGE: "ADD_MESSAGE",
  ADD_MESSAGES_LIST: "ADD_MESSAGES_LIST",
  SELECT_VISITOR: "SELECT_VISITOR",
  CLEAR_COUNTS: "CLEAR_COUNTS",
  MESSAGE_SEEN: "ADMIN_MESSAGE_SEEN",
  messages: {
    NEW_MESSAGE: "NEW_MESSAGE",
    ADD_MESSAGES_LIST: "ADD_MESSAGES_LIST",
    SEEN: "SEEN",
    SELECT_CONVERSATION: "SELECT_CONVERSATION",
  },
};

export const PlexarChatActions = {
  SELECT_CONVERSATION: "PL_SELECT_CONVERSATION",
  ADD_CONVERSATION_LIST: "PL_ADD_CONVERSATION_LIST",
  NEW_MESSAGE: "PL_NEW_MESSAGE",
  ADD_MESSAGES_LIST: "PL_ADD_MESSAGES_LIST",
  NEW_CONVERSATION: "PL_NEW_CONVERSATION",
  REMOVE_COMVERSATION: "PL_REMOVE_COMVERSATION",
  CLEAR_COUNTS: "PL_CLEAR_COUNTS",
  SEEN_MESSAGE: "PL_SEEN_MESSAGE",
  CALLED_CONVERSATION_API: "PL_CALLED_CONVERSATION_API",
  CONVERSATION_CLOSED: "PL_CONVERSATION_CLOSED",
};

export const InboxActions = {
  NEW_MESSAGE: "NEW_MESSAGE",
  ADD_MESSAGES_LIST: "ADD_MESSAGES_LIST",
  SEEN_MESSAGE: "SEEN_MESSAGE",
};
